name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays at midnight
  workflow_dispatch: # Allow manual triggers

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Check for outdated packages
        run: npm outdated

      - name: Update dependencies
        run: npx npm-check-updates -u && npm install

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: update dependencies"
          body: "Automated dependency updates by GitHub Actions"
          branch: "dependencies/update"
          base: "main"
          labels: "dependencies"